name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Provide externalized variables
      run: |
          cp testing.env .env
    - name: Make Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
